Refactored pip installs for virtual environments.

diff --git a/bin/hr2_install b/bin/hr2_install
--- a/bin/hr2_install
+++ b/bin/hr2_install
@@ -84,12 +84,12 @@ set -u           # Treat unset variables as an error.
 # Set all of the install flags to the empty string.  Set to "yes" to enable.
 # The following test will do the logical OR of given flags `if [ -n "$EE$ME" ]`.
 # It is basically the same as `if [ -n "$EE" ] || [ -n "ME" ]`, but little shorter:
-DEV="    # Development
+DEV=""   # Development
 EE=""    # Electrical Engineering
 ME=""    # Mechanical Engineering
 SW=""    # Software
 WF=""    # Workflow
-PASS2="" # Secret flag to enter the recursive portion of this shell script
+PASS2=""  # Secret flag to enter the recursive portion of this shell script
 
 # Process the arguments specified by the user:
 if [ "$#" == "0" ]
@@ -99,7 +99,7 @@ then
     echo "where:"
     echo "all    Installs everything"
     echo "most   Installs everything but dev"
-    echo "dev    Installs the development workflow stuff (a personal Git.Hub account is required.)"
+    echo "dev    Installs the development workflow (a personal Git.Hub account is required.)"
     echo "ee     Installs all of the software needed for electrical engineering"
     echo "me     Installs all of the software needed for mechanical engineering"
     echo "sw     Installs all of the software needed for software development"
@@ -164,8 +164,198 @@ cd $HR2_DIRECTORY
 if [ -z "$PASS2" ]
 then
     # Pass1:
-    #echo "Pass 1"
+    echo "Pass 1"
 
+    # The master branch is configured to be "read-only in the sense that it is *NEVER* modified on
+    # the local machine.  Modifications on other branches are allowed, but not to the local master.
+    # What this means is that it is always safe to do a `git pull` into the master branch.  We do
+    # not over think this, we just attempt to checkout master and do the pull.  If it fails, we let
+    # you know that the checkout failed.  This functionality is embedded in the fairly complicated
+    # shell function below.
+
+    # Usage `repository_update REPOSITORY_DIRECTORY`
+    # Returns 0 for success and > 0 for errors:
+    function repository_update() {
+	# Step 1: Extract the REPOSITORY_DIRECTORY function argument:
+        echo "Step 1"
+	REPOSITORY_DIRECTORY=$1
+	#debug: echo "REPOSITORY_DIRECTORY=$REPOSITORY_DIRECTORY"
+	ERROR_MESSAGE='Update of repository for "$REPOSITORY_DIRECTORY" will not happen.'
+	# CWD means Current Working Directory:
+	CWD=`pwd`
+
+	# Step 2: Ensure that we have `git` is installed:
+	WHICH_GIT=`which git`
+	#debug: echo "WHICH_GIT=$WHICH_GIT"
+	if [ -z "$WHICH_GIT" ]
+	then
+	    echo "!!!!!!!!!!!!!!!! \`git\` program is not installed yet."
+            echo "$ERROR_MESSAGE"
+	    return 1
+	fi
+
+	# Step 2: Ensure that REPOSITORY_DIRECTORY exists and is a directory.
+        echo "Step 2"
+	if [ ! -d "$REPOSITORY_DIRECTORY" ]
+	then
+	    echo "!!!!!!!!!!!!!!!! \`$REPOSITORY_DIRECTORY\` is not a directory."
+            echo "ERROR_MESSAGE"
+	    return 2
+	fi
+
+	# Step 3: Change over to REPOSITORY_DIRECTORY and find the REPOSITORY_ROOT.  From here on,
+	# before returning we have to return to the original CWD directory on an error.
+        echo "Step 3"
+	cd "$REPOSITORY_DIRECTORY"
+	# The `2>/dev/null` suppresses error messages:
+	REPOSITORY_ROOT=`git rev-parse --show-toplevel 2>/dev/null`
+	#debug: echo "REPOSITORY_ROOT=$REPOSITORY_ROOT"
+	if [ -z "$REPOSITORY_ROOT" ]
+	then
+	    echo "!!!!!!!!!!!!!!!! \`$REPOSITORY_DIRECTORY\` is not part of a git repository."
+            echo "$ERROR_MESSAGE"
+            cd "$CWD"
+	    return 3
+	fi
+
+	# Step 4: Determine if with we have either an `upstream` or `origin` remote.  If the
+	# repository has been freshly cloned, it will have a remote of `origin`.  If the
+	# `hr2_install dev` has been specified it has been set up as `upstream`.  If neither
+	# remote is present, there is no way to recover and we are done.  We may have the
+	# `set -o pipefail` option enabled and the code below avoids problems with `grep` not
+	# finding anything.
+        echo "Step 4"
+	UPSTREAM_REMOTE=`( cd $HR2_DIRECTORY ; echo $(git remote | grep upstream) )`
+	ORIGIN_REMOTE=`( cd $HR2_DIRECTORY ; echo $(git remote | grep origin) )`
+	echo "ORIGIN_REMOTE=$ORIGIN_REMOTE"
+	echo "UPSTREAM_REMOTE=$UPSTREAM_REMOTE"
+	if [ -n "$UPSTREAM_REMOTE" ]
+	then
+	    ACTUAL_REMOTE="$UPSTREAM_REMOTE"
+	elif [ -n "$ORIGIN_REMOTE" ]
+	then
+	    ACTUAL_REMOTE="$ORIGIN_REMOTE"
+	else
+	    echo "!!!!!!!!!!!!!!!! There is no remote repository named \`upstream\`" \
+		 "or \'origin\' defined for repository \'$REPOSITORY_ROOT\'."
+	    echo "$ERROR_MESSAGE"
+	    cd "$CWD"
+	    return 4
+	fi
+
+	# Step 5: Determine if we have a `master` branch.  If not, things pretty screwed up.
+	# `git branch` returns an alphabetized of branches of the form:
+	#
+	#       branch1
+	#     * branch2
+	#       ...
+	#       branchN
+	#
+	# The currently active branch will have an asterisk in front of it.
+	# We feed the output of `git branch` through `sed` to strip off the first two
+	# characters and search for `master`:
+        echo "Step 5"
+	MASTER_BRANCH=`git branch | sed "s,^..,,g" | grep master`
+	#debug: echo "MASTER_BRANCH=$MASTER_BRANCH"
+	if [ -z "$MASTER_BRANCH" ]
+	then
+	    echo "!!!!!!!!!!!!!!!! There is no \`master\` branch in repository \`$REPOSITORY_ROOT\`."
+	    echo "$ERROR_MESSAGE"
+	    cd "$CWD"
+	    return 5
+	fi
+
+	# Step 6: Get current branch name and a list of uncommitted files.  If we are not on the
+	# `master` branch we will temporarily switch over to the `master` branch, attempt to update
+	# master and return the current branch.  This is easily said, not not so easily done.
+	# If we are already on the `master` branch we can avoid the hassle of switching branches:
+	# For reference:
+	#   https://stackoverflow.com/questions/6245570/how-to-get-the-current-branch-name-in-git
+	# explained how to get the CURRENT_BRANCH name.  It is obscure:
+	CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`
+	#debug: echo "CURRENT_BRANCH=$CURRENT_BRANCH"
+	# Likewise getting the UNCOMMITTED_FILES is pretty obscure as well:
+	UNCOMMITTED_FILES=`git diff --name-only HEAD`
+	#debug: echo "UNCOMMITTED_FILES=$UNCOMMITTED_FILES"
+	echo "Step 6"
+	echo "Starting to update the master branch."
+	if [ "$CURRENT_BRANCH" != "master" ]
+	then
+	    # Step 6: We have uncommitted files in this repository. We need to
+	    # temporarily "stash" them before changing over to `master` branch:
+	    if [ -n "$UNCOMMITTED_FILES" ]
+	    then
+		echo "Temporarily stashing uncommitted files for \`$CURRENT_BRANCH\` branch."
+		git stash > /dev/null # Suppress the messages.
+	    fi
+
+	    # Step 7: Temporarily switch over to `master` branch:
+	    echo "Temporarily switching over to master branch from $CURRENT_BRANCH branch."
+            # Suppress the messages:
+	    git checkout master > /dev/null 2>/dev/null
+	    # From here on out, if we encounter an error we have return back to `$CURRENT_BRANCH`
+	    # **AND** unstash the uncommitted files.
+	fi
+
+	# Step 7: Finally perform the git pull from the upstream/orign repository into
+	# the master branch.  Because the local master branch has been configured
+	# to disallow commits, in theory, there can be no can be no merge conflicts:
+	echo "Step 7"
+        git checkout master
+	git pull "$ACTUAL_REMOTE" master # 2>/dev/null 1>/dev/null # Suppress the output
+	echo "master branch should be up to date"
+
+	# Step 8: Now we return to the original branch we started (if necessary):
+	echo "Step 8"
+	if [ "$CURRENT_BRANCH" != "master" ]
+	then
+	    echo "Switch from master branch back to $CURRENT_BRANCH branch."
+	    git checkout $CURRENT_BRANCH > /dev/null 2>/dev/null # Suppess the messages
+
+	    # Step 9: Now restore the branch to the way it was:
+	    echo "Restore any previously uncommitted files."
+	    git stash pop > /dev/null  # `> /dev/null` suppresses an unneeded `git status`
+
+	    # We are back in CURRENT_BRANCH with any uncommitted files restored.
+	fi
+	
+	# The following code merges to the CURRENT_BRANCH, which is currently not enabled:
+	#    # The following is a references (* is the one selected):
+	#    #
+	#    #     * https://code-maven.com/git-check-for-conflicts-before-merge
+	#    #       https://stackoverflow.com/questions/501407/is-there-a-git-merge-dry-run-option
+	#    #       https://stackoverflow.com/questions/964876/head-and-orig-head-in-git
+	#    #
+        #    # Now figure out if a merge from master will have any conflicts.
+	#    # This is done by doing a `git merge --no-commit`, followed by a
+	#    # `git merge -abort`.  The return code from the `--no-commit`
+	#    # is used to decide whether to do the actual merge or not.
+	#    # If no conlicts will occur, perform the merge to this branch:
+	#    echo "Performing test merge from master branch to $CURRENT_BRANCH."
+	#    if git merge --no-commit --no-ff master > /dev/null 2>/dev/null # Suppress messages
+	#    then
+	#	echo "Test merge shows no problems.  Undo test merge and do it for real."
+	#	git merge --abort 2>/dev/null  # `2>/dev/null` suppresses "fatal: ...." message
+	#	echo "Performing the actual merge from the master branch to $CURRENT_BRANCH branch."
+	#	# Suppress error messages:
+	#	git merge master --commit --no-ff --no-edit > /dev/null 2>/dev/null
+	#    else
+	#	echo "Test merge shows there will be issue merging master branch" \
+	#	     " to $CURRENT_BRANCH branch."
+	#	echo "Undoing the test merge."
+	#	git merge --abort
+	#	echo "Please add your modified files into your branch with git add."
+	#	echo "When they are all added, please do a git commit."
+	#	echo "Then rerun the shell script again."
+	#    fi
+	#fi
+
+	# We are done, so return to CWD and return:
+	cd "$CWD"
+        echo "Done"
+	return 0
+    }
+ 
     # Make sure that `git` exists:
     if [ -z `which git` ]
     then
@@ -197,12 +387,7 @@ then
     # In theory, there the local copy of the `master` branch is locked down and can not
     # be branched because we install a pre-commit hook to disallow commits to the `master`
     # branch (see further below.)   This means that a `git pull` should always succeed.
-    if [ ! git pull $ACTUAL_REMOTE master ]
-    then
-	echo "For some reason the update of the \`master\` branch of the \`HR2_DIRECTORY\` failed."
-	echo "This error can not be recovered from from.  This script is immediately stopping."
-	exit 3
-    fi
+    repository_update "$HR2_DIRECTORY"
 	
     # Now this file may have been updated as a result of the `git pull`, so we recursively
     # call the this script (which may have been updated):
@@ -734,7 +919,6 @@ fi
 # Install the Python stuff for both ME and EE:
 if [ -n "$PYTHON_NEEDED" ]
 then
-    echo "here 1"
     if [ -z "`which virtualenvwrapper.sh`" ]
     then
 	echo "For some reasons virtualenvwrapper.sh did not get installed.  This is bad."
@@ -743,22 +927,18 @@ then
     fi
 
     # The virtual wrapper script breaks under debugging, so turn all debugging is now turned off.
-    echo "here 2"
     set +x           # Trace execution.
     set +e           # Exit immediately on error result.
     set +o pipefail  # Fail if any commands in a pipeline fail.
     set +u           # Treat unset variables as an error.
 
     # We should have a hot Python virtual environment:
-    echo "here 3"
     source "`which virtualenvwrapper.sh`"
 
-    # Now ensure that the hr2 pythong virtual environment exists:
+    # Now ensure that the hr2 Python virtual environment exists:
     MKVIRTUALENV="mkvirtualenv -p 3.6" 
-    echo "here 4"
     if [ ! -d $WORKON_HOME/hr2 ]
     then
-    echo "here 5"
 	echo "**************** Create hr2 python virtual environment ..."
 	$MKVIRTUALENV -a $HR2_DIRECTORY hr2
     else
@@ -768,92 +948,86 @@ then
     # For some weird reason, doing a "source $BASHRC" does not properly get
     # the virtual environment wrapper variables set properly.  So, instead
     # we set them all manually below:
-    echo "here 6"
     export VIRTUALENVWRAPER_PYTHON=`which python3`
     export WORKON_HOME=$WORKON_HOME
     export REPOSITORIES_DIRECTORY=$REPOSITORIES_DIRECTORY
     export VIRTUALENVWRAPER_WORKON_CD=1
 
+    # Python virtual environments are not recursive.  This means that if one has been activated
+    # that we should not attempt to activate another.  We deal with all of this complexity with
+    # the shell function below.
+    # Usage `hr2_env_pip_install ENV_NAME PROGRAM_NAME_OR_DIRECTORY`
+    # `ENV_NAME` is the virtual environment name, and
+    # `PROGRAM_NAME_OR_DIRECTORY` is the program name or Python directory to be installed
+    function python_env_pip_install() {
+	# Exactly two arguments are required:
+	if [ "$#" != "2" ]
+	then
+	    echo "\`python_env_pip_install\` called with $# arguments instead of just 2."
+	    return 1
+	fi
+
+	# Extract the arguments and give them names:
+	ENV_NAME="$1"
+	PROGRAM_NAME_OR_DIRECTORY="$2"
+
+	# Make sure there is an `ENV_DIRECTORY` exists:
+        ENV_DIRECTORY="$WORKON_HOME/$ENV_NAME"
+	if [ ! -d "$ENV_DIRECTORY" ]
+	then
+	    echo "\`$ENV_DIRECTORY\` does not exist."
+	    return 2
+	fi
+	
+        # Figure out if the ENV_NAME is active or not:
+	if [ -z "${VIRTUAL_ENV+EXISTS}" ]
+	then
+	    # `VIRTUAL_ENV` is not enabled, so we can activate one, install and deactivate:
+	    (workon "$ENV_NAME"
+	     $PIP_INSTALL "$PROGRAM_NAME_OR_DIRECTORY"
+	     deactivate)
+	else
+	    # `VIRTUAL_ENV` is enabled.
+
+	    # There is an active environment, but doe it match `ENV_NAME`?
+	    ACTUAL_ENV_NAME=`echo $VIRTUAL_ENV | sed "s,^.*/,,g"`
+	    if [ "$ACTUAL_ENV_NAME" != "$ENV_NAME" ]
+	    then
+		echo "Currently active Python virtual environment is" \
+		     "\`$ACTUAL_ENV_NAME\` not \`$ENV_NAME\`."
+		return 3
+	    fi
+	    
+	    # We can just do a simple `PIP_INSTALL`:
+	    $PIP_INSTALL "$PROGRAM_NAME_OR_DIRECTORY"
+	fi
+    }
+
     # Install Python mypi static type checker:
-    if [ -z "`which mypy`" ]
-    then
-        echo "here 7"
-	echo "Installing Python mypy static type checker ..."
-	(workon hr2; $PIP_INSTALL mypy ; deactivate)
-    else
-	echo "Python mypy static type checker previously installed."
-    fi
+    python_env_pip_install hr2 mypy
 
     # Install Python flake8 code style checker:
-    if [ -z "`which flake8`" ]
-    then
-        echo "here 8"
-	echo "**************** Installing Python flake8 code style checker ..."
-	(workon hr2; $PIP_INSTALL flake8 ; deactivate)
-    else
-	echo "Python flake8 code style checker previously installed."
-    fi
+    python_env_pip_install hr2 flake8
 
     # Install Python pydocstyle documentation style checker:
-    if [ -z "`which pydocstyle`" ]
-    then
-        echo "here 9"
-	echo "**************** Installing Python pydocstyle documentation style checker ..."
-	(workon hr2; $PIP_INSTALL pydocstyle ; deactivate)
-    else
-	echo "Python pydocstyle documentation style checker previously installed."
-    fi
+    python_env_pip_install hr2 pydocstyle
 
     # Install pytest testing system:
-    if [ -z "`which pytest`" ]
-    then
-        echo "here 10"
-	echo "**************** Installing Python testing system ..."
-	( workon hr2; $PIP_INSTALL pytest ; deactivate )
-    else
-	echo "Python testing system previously installed."
-    fi
+    python_env_pip_install hr2 pytest
 
-    # Install kipart, kicube32, bom_manager:
-    echo "here 10"
+    # Install kipart, kicube32, bom_manager for EE:
     if [ -n "$EE" ]
     then
 	# Install kipart into hr2 environment:
-        echo "here 11"
-	(workon hr2
-	 echo "here 12"
-	 if [ -z `which kipart` ]
-	 then
-	     echo "here 13"
-	     echo "**************** Installing kipart into hr2 virtual environment..."
-	     pip3 install kipart
-	     echo "here 14"
-	 else
-	     echo "here 15"
-	     echo "kipart previously installed into hr2 virtual environment."
-	 fi
-	 echo "here 16"
-	 deactivate)
-	echo "here 17"
+        python_env_pip_install hr2 kipart
 
 	# Install kicube32 into hr2 environment:
-	echo "Installing kicube32 into hr2 virtual environment."
-	(workon hr2
-	 if [ -z `which kicube32` ]
-	 then
-	     echo "**************** Installing kicube32 into hr2 virtual environment..."
-	     $PIP_INSTALL $REPOSITORIES_DIRECTORY/kicube32
-	 else
-	     echo "kicube32 previously installed into hr2 virtual environment..."
-	 fi
-	 deactivate)
+        KICUBE32_DIRECTORY="$REPOSITORIES_DIRECTORY/kicube32"
+        python_env_pip_install hr2 "$KICUBE32_DIRECTORY"
 
 	# For now do not bother with `bom_manager`.
     fi
 fi
-
-# Remind the user that they are on the `master` branch:
-echo "Please note that you are on the branch named \`master\` for the $HR2_DIRECTORY repository."
 
 # Remind the user to update their top-level `bash` environment:
 if [ -n "SOURCE_BASHRC" ]
